IL_batch_size: 2048
argv: '[''main.py'', ''DS-AL'', ''--dataset'', ''ImageNet-1k'', ''--base-ratio'',
  ''0.5'', ''--phases'', ''2'', ''--data-root'', ''~/dataset'', ''--IL-batch-size'',
  ''2048'', ''--num-workers'', ''8'', ''--backbone'', ''resnet18'', ''--gamma'', ''0.1'',
  ''--gamma-comp'', ''0.1'', ''--compensation-ratio'', ''1.5'', ''--buffer-size'',
  ''8192'', ''--cache-features'', ''--backbone-path'', ''./backbones/resnet18_ImageNet-1k_0.5_None'']'
backbone: resnet18
backbone_path: ./backbones/resnet18_ImageNet-1k_0.5_None\backbone.pth
base_epochs: 300
base_ratio: 0.5
batch_size: 256
buffer_size: 8192
cache_features: true
cache_path: ./backbones/resnet18_ImageNet-1k_0.5_None
compensation_ratio: 1.5
cpu_only: false
data_root: C:\Users\86182/dataset
dataset: ImageNet-1k
dataset_seed: null
exp_name: DS-AL
gamma: 0.1
gamma_comp: 0.1
gpus: null
label_smoothing: 0.05
learning_rate: 0.5
method: DS-AL
momentum: 0.9
num_workers: 8
phases: 2
saving_root: saved_models\resnet18_ImageNet-1k_0.5_None\DS-AL\2025-02-17T11-27-39
seed: null
separate_decay: false
sigma: 10
warmup_epochs: 10
weight_decay: 0.0005
