IL_batch_size: 4096
argv: '[''main.py'', ''ACIL'', ''--dataset'', ''CIFAR-100'', ''--base-ratio'', ''0.5'',
  ''--phases'', ''25'', ''--data-root'', ''~/dataset'', ''--batch-size'', ''256'',
  ''--num-workers'', ''16'', ''--backbone'', ''resnet32'', ''--learning-rate'', ''0.5'',
  ''--label-smoothing'', ''0'', ''--base-epochs'', ''300'', ''--weight-decay'', ''5e-4'',
  ''--gamma'', ''0.1'', ''--buffer-size'', ''8192'', ''--cache-features'', ''--IL-batch-size'',
  ''4096'']'
backbone: resnet32
base_epochs: 300
base_ratio: 0.5
batch_size: 256
buffer_size: 8192
cache_features: true
cache_path: null
compensation_ratio: 1
cpu_only: false
data_root: C:\Users\86182/dataset
dataset: CIFAR-100
dataset_seed: null
exp_name: ACIL
gamma: 0.1
gamma_comp: 0.1
gpus: null
label_smoothing: 0.0
learning_rate: 0.5
method: ACIL
momentum: 0.9
num_workers: 16
phases: 25
saving_root: saved_models\resnet32_CIFAR-100_0.5_None\ACIL\2025-02-16T22-49-40
seed: null
separate_decay: false
sigma: 10
warmup_epochs: 10
weight_decay: 0.0005
