IL_batch_size: 2048
argv: '[''main.py'', ''DS-AL'', ''--dataset'', ''CIFAR-100'', ''--base-ratio'', ''0.5'',
  ''--phases'', ''5'', ''--data-root'', ''~/dataset'', ''--IL-batch-size'', ''2048'',
  ''--num-workers'', ''8'', ''--backbone'', ''resnet32'', ''--gamma'', ''0.1'', ''--gamma-comp'',
  ''0.1'', ''--compensation-ratio'', ''0.6'', ''--buffer-size'', ''4096'', ''--cache-features'',
  ''--backbone-path'', ''./backbones/resnet32_CIFAR-100_0.5_None'']'
backbone: resnet32
backbone_path: ./backbones/resnet32_CIFAR-100_0.5_None\backbone.pth
base_epochs: 300
base_ratio: 0.5
batch_size: 256
buffer_size: 4096
cache_features: true
cache_path: ./backbones/resnet32_CIFAR-100_0.5_None
compensation_ratio: 0.6
cpu_only: false
data_root: C:\Users\86182/dataset
dataset: CIFAR-100
dataset_seed: null
exp_name: DS-AL
gamma: 0.1
gamma_comp: 0.1
gpus: null
label_smoothing: 0.05
learning_rate: 0.5
method: DS-AL
momentum: 0.9
num_workers: 8
phases: 5
saving_root: saved_models\resnet32_CIFAR-100_0.5_None\DS-AL\2025-02-17T11-08-21
seed: null
separate_decay: false
sigma: 10
warmup_epochs: 10
weight_decay: 0.0005
